spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timestamps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    com.leon: DEBUG
